// <auto-generated />
using System;
using FinancialTools.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinancialTools.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FinancialToolsDbContext))]
    partial class FinancialToolsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("FNCT")
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinancialTools.Domain.BankAccounts.BankAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Bank")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OpenedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BankAccounts", "FNCT");
                });

            modelBuilder.Entity("FinancialTools.Domain.CashAccounts.CashAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsElegibleForPayment")
                        .HasColumnType("boolean");

                    b.Property<string>("LastLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CashAccounts", "FNCT");
                });

            modelBuilder.Entity("FinancialTools.Domain.CreditCards.CreditCard", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Bank")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OpenedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("CreditCards", "FNCT");
                });

            modelBuilder.Entity("FinancialTools.Domain.CreditCards.CreditCardAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreditCardId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CreditLimit")
                        .HasColumnType("numeric");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("CurrentBalance")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LastStatementBalance")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CreditCardId");

                    b.ToTable("CreditCardAccounts", "FNCT");
                });

            modelBuilder.Entity("FinancialTools.Domain.BankAccounts.BankAccount", b =>
                {
                    b.OwnsOne("FinancialTools.Domain.Common.CardDetails", "DebitCard", b1 =>
                        {
                            b1.Property<Guid>("BankAccountId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CVV")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CardHolder")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("Network")
                                .HasColumnType("integer");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("BankAccountId");

                            b1.ToTable("BankAccounts", "FNCT");

                            b1.WithOwner()
                                .HasForeignKey("BankAccountId");

                            b1.OwnsOne("FinancialTools.Domain.Common.ValueObjects.CardExpirationDate", "ExpirationDate", b2 =>
                                {
                                    b2.Property<Guid>("CardDetailsBankAccountId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Month")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Year")
                                        .HasColumnType("integer");

                                    b2.HasKey("CardDetailsBankAccountId");

                                    b2.ToTable("BankAccounts", "FNCT");

                                    b2.WithOwner()
                                        .HasForeignKey("CardDetailsBankAccountId");
                                });

                            b1.Navigation("ExpirationDate")
                                .IsRequired();
                        });

                    b.Navigation("DebitCard");
                });

            modelBuilder.Entity("FinancialTools.Domain.CreditCards.CreditCard", b =>
                {
                    b.OwnsOne("FinancialTools.Domain.Common.CardDetails", "CardInfo", b1 =>
                        {
                            b1.Property<Guid>("CreditCardId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CVV")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CardHolder")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("Network")
                                .HasColumnType("integer");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("CreditCardId");

                            b1.ToTable("CreditCards", "FNCT");

                            b1.WithOwner()
                                .HasForeignKey("CreditCardId");

                            b1.OwnsOne("FinancialTools.Domain.Common.ValueObjects.CardExpirationDate", "ExpirationDate", b2 =>
                                {
                                    b2.Property<Guid>("CardDetailsCreditCardId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Month")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Year")
                                        .HasColumnType("integer");

                                    b2.HasKey("CardDetailsCreditCardId");

                                    b2.ToTable("CreditCards", "FNCT");

                                    b2.WithOwner()
                                        .HasForeignKey("CardDetailsCreditCardId");
                                });

                            b1.Navigation("ExpirationDate")
                                .IsRequired();
                        });

                    b.OwnsOne("FinancialTools.Domain.CreditCards.CreditCardStatementDate", "StatementDate", b1 =>
                        {
                            b1.Property<Guid>("CreditCardId")
                                .HasColumnType("uuid");

                            b1.Property<int>("DayOfTheMonth")
                                .HasColumnType("integer");

                            b1.Property<int>("PaymentDueDateDaysOffset")
                                .HasColumnType("integer");

                            b1.HasKey("CreditCardId");

                            b1.ToTable("CreditCards", "FNCT");

                            b1.WithOwner()
                                .HasForeignKey("CreditCardId");
                        });

                    b.Navigation("CardInfo")
                        .IsRequired();

                    b.Navigation("StatementDate")
                        .IsRequired();
                });

            modelBuilder.Entity("FinancialTools.Domain.CreditCards.CreditCardAccount", b =>
                {
                    b.HasOne("FinancialTools.Domain.CreditCards.CreditCard", null)
                        .WithMany("Accounts")
                        .HasForeignKey("CreditCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FinancialTools.Domain.CreditCards.CreditCard", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
